### Recuperar todas las peliculas
GET http://localhost:1234/movies

### Recuperar una pelicula por genero
GET http://localhost:1234/movies?genre=Action

### Recuperar una pelicula por titulo
GET http://localhost:1234/movies?title=The%20Dark%20Knight

### Recuperar una pelicula por año
GET http://localhost:1234/movies?year=1999

### Recuperar una pelicula por director
GET http://localhost:1234/movies?director=Christopher%20Nolan

### Recuperar una pelicula por id
GET http://localhost:1234/movies/dcecedae-549e-11f0-9b26-b42e999d9c15

### Crear una pelicula
POST http://localhost:1234/movies
Content-Type: application/json

{
  "title": "The Godfather",
  "year": 1975,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "genre": [
    "Crime",
    "Drama"
  ],
  "rate": 9.2
}

### Actualizar una pelicula
PATCH  http://localhost:1234/movies/3ea0676f-549f-11f0-9b26-b42e999d9c15
Content-Type: application/json

{
  "year": 1993
}

### Eliminar una pelicula
DELETE http://localhost:1234/movies/3ea0676f-549f-11f0-9b26-b42e999d9c15

### --------> Recperar peliculas por parametros incorrectos
### Recuperar una pelicula por genero incorrecto
GET http://localhost:1234/movies?title=pepe

### Crear una pelicula incorrecta
POST http://localhost:1234/movies
Content-Type: application/json

{
  "title": 8,
  "year": "jsjs",
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "hola"
}

### Intento de insection SQL
POST http://localhost:1234/movies
Content-Type: application/json

{
  "sql": "SELECT * FROM users",
  "title": "The Godfather",
  "year": 1975,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "genre": [
    "Crime",
    "Drama"
  ],
  "rate": 9.2
}